#!/usr/bin/env python3
"""
build.py — generates pages/timeline-content.js from individual HTML partial files.

Run this any time you edit a file in pages/timeline-content/:
    python3 build.py

The generated file is loaded by pages/timeline.html and provides the content
for each timeline section without needing a server or fetch().
"""

import os, json, re

CONTENT_DIR = 'pages/timeline-content'
OUTPUT_FILE = 'pages/timeline-content.js'

files = sorted(os.listdir(CONTENT_DIR))
entries = {}

for fname in files:
    if not fname.endswith('.html'):
        continue
    key = 'timeline-content/' + fname
    fpath = os.path.join(CONTENT_DIR, fname)
    with open(fpath, 'r', encoding='utf-8') as f:
        html = f.read().strip()
    entries[key] = html

# Write JS file
with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
    f.write('// AUTO-GENERATED by build.py — do not edit directly.\n')
    f.write('// Edit files in pages/timeline-content/ and run: python3 build.py\n\n')
    f.write('window.timelineContent = ')
    f.write(json.dumps(entries, ensure_ascii=False, indent=2))
    f.write(';\n')

print(f"Generated {OUTPUT_FILE} with {len(entries)} entries:")
for k, v in entries.items():
    status = f"{len(v)} chars" if v else "empty stub"
    print(f"  {k}: {status}")
